REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO early_mind_app;
GRANT USAGE, CREATE ON SCHEMA public TO early_mind_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE early_mind_migrator IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO early_mind_app;
ALTER DEFAULT PRIVILEGES FOR ROLE early_mind_migrator IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO early_mind_app;
